version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    command: node dist/main.js
    environment:
      NODE_ENV: development