version: '3.8'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"

    command: node ./dist/main.js
    environment:
      NODE_ENV: development